jobs:
- job: 'Build'  
  strategy:
    matrix:
      linux_node-12.x:
        imageName: 'ubuntu-16.04'
        node_version: 12.x
      windows:
        imageName: 'vs2017-win2016'
        node_version: 12.x
      macOS:
        imageName: 'macos-10.13'
        node_version: 12.x

  pool:
    vmImage: $(imageName)

  steps:
    - task: NodeTool@0
      displayName: 'Use node $(node_version)'
      inputs:
        versionSpec: $(node_version)
    - task: Npm@1
      displayName: 'Install dependencies'
      inputs:
        command: install
        verbose: false
    - task: Npm@1
      displayName: 'Compile TypeScript'
      inputs:
        command: custom
        customCommand: 'run test-compile'
        verbose: false
    - task: Bash@3
      displayName: 'Start xvfb if running Linux'
      # Only run this task if the OS is linux
      condition: eq(variables['Agent.OS'], 'Linux')
      inputs:
        verbose: false
        targetType: 'inline'
        script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
    - task: Npm@1
      displayName: 'Run tests via vscode test script'
      env:
        DISPLAY: :10
      inputs:
        verbose: false
        customCommand: 'run test'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TEST-*.xml'
        testRunTitle: '$(Agent.OS) (node: $(node_version))'